# Generated by Django 5.2.8 on 2025-11-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0002_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='vlibras_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
