# Generated by Django 5.2.8 on 2025-11-18 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0005_profile_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('type', models.CharField(choices=[('job', 'Vaga de Emprego'), ('interview', 'Oportunidade de Entrevista'), ('demand', 'Demanda/Projeto')], default='job', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('paused', 'Pausada')], default='open', max_length=20, verbose_name='Status')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa/Cliente')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='Faixa Salarial')),
                ('work_mode', models.CharField(blank=True, help_text='Ex: Remoto, Híbrido, Presencial', max_length=50, verbose_name='Modo de Trabalho')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
                ('skills', models.CharField(blank=True, help_text='Separe por vírgula', max_length=500, verbose_name='Habilidades')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo de Inscrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Carta de Apresentação')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Currículo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewing', 'Em Análise'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do Administrador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='global_app.opportunity', verbose_name='Oportunidade')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-applied_at'],
                'unique_together': {('opportunity', 'user')},
            },
        ),
    ]
