# Generated by Django 5.2.8 on 2025-11-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
